#  Latent Factor 모형 (PCA와 Latent Factor 모형)

Latent Factor 모형은 복잡한 사용자/영화 특성을 몇 개의 벡터로 간략화해보겠다는 모형<br>
평점을 사용자 요인 행렬, 별점 요인 행렬의 곱으로 이루어진 행렬로 보고, SVD등과 같은 방식으로 평점 예측<br>
어떤 특징?<br>
특정한 장르를 가진 영화 (예, 코미디, 액션, 드라마)에 대한 사용자 선호도<br>
사용자 요인 벡터 (예: 코미디(1), 액션(-3), 드라마(3))<br>
영화 장르 요소 (예: 코미디(1), 액션(3), 드라마(3))<br>


In [1]:
#PCA는 차원을 축소하되, 전형적인 특징을 구하는 것¶

In [2]:
import numpy as np
from numpy import linalg as la

In [3]:
user, item = 5, 3
X = np.random.rand(user, item)

In [4]:
X

array([[0.45576024, 0.85987623, 0.20338675],
       [0.188475  , 0.53533264, 0.11805839],
       [0.39010448, 0.23326821, 0.99165315],
       [0.13186816, 0.23455482, 0.65834147],
       [0.88851688, 0.36743842, 0.15361506]])

In [5]:
np.mean(X, axis=0)

array([0.41094495, 0.44609406, 0.42501097])

In [9]:
C = np.cov(X, rowvar=False)


# eigenvalue 구하기

l, principal_axes = la.eig(C)


l, principal_axes

(array([0.19783644, 0.08103821, 0.0275812 ]),
 array([[ 0.31172042,  0.92104406,  0.23346996],
        [ 0.44928242, -0.35938506,  0.81791667],
        [-0.83724291,  0.15006738,  0.52583656]]))

In [10]:
idx = l.argsort()[::-1]
l, principal_axes = l[idx], principal_axes[:, idx]

In [11]:
# l은 eigenvalue

l

array([0.19783644, 0.08103821, 0.0275812 ])

In [13]:
#  principal_axes 고유벡터
principal_axes

array([[ 0.31172042,  0.92104406,  0.23346996],
       [ 0.44928242, -0.35938506,  0.81791667],
       [-0.83724291,  0.15006738,  0.52583656]])

In [15]:
# 차원축소

principal_axes[:, :2]

array([[ 0.31172042,  0.92104406],
       [ 0.44928242, -0.35938506],
       [-0.83724291,  0.15006738]])

In [17]:
# 특정벡터추출

principal_components = X.dot(principal_axes)

principal_components

array([[ 0.35811294,  0.14127031,  0.91666162],
       [ 0.20042349, -0.00108006,  0.54394016],
       [-0.60384773,  0.42428509,  0.80331912],
       [-0.40470438,  0.13595647,  0.56881357],
       [ 0.31343935,  0.70936392,  0.58875242]])